//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hurricanesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hurricane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hurricane()
        {
            this.AffectedCounties = new HashSet<County>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime LandfallDate { get; set; }
        public int SaffirSimpsonCat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<County> AffectedCounties { get; set; }
    }
}
